export const ERROR_MESSAGES = {
  folderNotFound: 'Папка не найдена',
  parentFolderNotFound: 'Parent folder not found',
  destinationFolderNotFound: 'Папка назначения не найдена',
  fileNotFound: 'Файл не найден',
  articleNotFound: 'Статья не найдена',
  notFound: 'Not found',
  folderNameRequired: 'Folder name required',
  folderNameTooLong: 'Folder name is too long',
  fileNameEmpty: 'Имя файла не может быть пустым',
  fileNameTooLong: 'Имя файла слишком длинное',
  titleEmpty: 'Заголовок не может быть пустым',
  titleTooLong: 'Заголовок слишком длинный',
  annotationTooLong: 'Аннотация слишком длинная',
  invalidTags: 'Некорректные теги',
  tooManyTags: 'Слишком много тегов',
  tagTooLong: 'Тег слишком длинный',
  invalidStatus: 'Недопустимый статус',
  invalidRequest: 'Некорректные данные запроса',
  invalidArticleContent: 'Некорректное содержимое статьи',
  invalidPassword: 'Неверный пароль',
  tooManyAttempts: 'Слишком много попыток. Попробуйте позже.',
  storageFull: (maxGb: number) => `Хранилище заполнено. Максимальный объём — ${maxGb} ГБ`,
  fileTooLarge: (maxMb: number) => `Файл превышает лимит ${maxMb} МБ`,
  unsupportedFileType: (mime: string) => 'Unsupported file type: ' + mime,
  invalidOrigin: 'Недопустимый источник запроса',
} as const;
